services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: postgres://myuser:mypassword@db:5432/mydb?sslmode=disable
    networks:
      - webnet

  frontend:
    build: ./frontend
    ports:
      - "3000:4173"
    depends_on:
      - backend
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - db
      - backend
      - frontend
    networks:
      - webnet

volumes:
  pgdata:

networks:
  webnet:
